//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_esclab : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean SelectWall
        {
            get
            {
                return SteamVR_Actions.esclab_SelectWall;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateWall
        {
            get
            {
                return SteamVR_Actions.esclab_RotateWall;
            }
        }
        
        public virtual SteamVR_Action_Boolean DisplayStats
        {
            get
            {
                return SteamVR_Actions.esclab_DisplayStats;
            }
        }
    }
}
